
name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
runs:
  steps:
  - uses: actions/checkout@v1
  - name: Use Node.js 12
    uses: actions/setup-node@v1
    with:
      node-version: '12.x'
  - name: Install dependencies
    run: node ./dist/index.js
