name: 'Workflow Legal ⭐'

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 
      env:
        repo-token: '${{ github.token }}'
        configuration-path: '.github/labeler.yml'
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        repo-token: '${{ github.token }}'
        configuration-path: '.github/labeler.yml'
    - run: npm install
    - run: npm run pack
      
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(env) }}
      run: echo "$MATRIX_CONTEXT"
  
  
    - uses: actions/checkout@v2
      with:
        path: ./
    - uses: ./.github/actions/my-action
      with: 
        path: ./
        repo-token: '${{ github.token }}'
        configuration-path: '.github/labeler.yml'
      env:
        CI: true
        repo-token: '${{ github.token }}'
        configuration-path: '.github/labeler.yml'

